project:
  type: book

book:
  title: "PL, NGP och Seqera"
  author: "Halfdan Rydbeck"
  date: "2024-10-24"
  chapters:
    - index.qmd
    - chapters/centrala_uppgifter.qmd
    - chapters/hårdvara.qmd
    - chapters/executors.qmd
    - chapters/PL_sammanhang_och_funktion_inom_RO.qmd
    - chapters/Sekvenserings_och_klinisk_data.qmd
    - chapters/pl_ngs.qmd
    - chapters/vad_är_ett_arbetsflöde.qmd
    - chapters/pl_gemensamt.qmd
    - chapters/PL_sammanhang_och_funktion_inom_GMS.qmd
    - chapters/vad_är_NGP.qmd
    - chapters/vad_är_GMS.qmd
    - chapters/vision_för_europeikst_datadelningsnätverk.qmd
    - chapters/upplastning_av_data_NGP.qmd
    - chapters/NGP_är_tänkt_att_i_huvudsak_köra_bioinformatiska_arbetsflöden.qmd
    - chapters/Sällsynta_diagnoser_arbetsflöde.qmd
    - chapters/Sällsynta_diagnoser_arbetsflöde_utvecklat_av_nf_core.qmd
    - chapters/det_är_inte_enkelt_att_utveckla_och_köra_bioinforamtiska_arbetsflöden.qmd
    - chapters/arbetsflödes_hanterings_program_Nextflow_del_1.qmd
    - chapters/arbetsflödes_hanterings_program_Nextflow_del_2.qmd
    - chapters/vad_kan_versionskontrolleras.qmd
    - chapters/git_ett_system_för_versionskontrollering.qmd
    - chapters/2_kollektiv_versionskontrollerad_mjukvaru_utvecking_med_git_och_Github_A.qmd
    - chapters/2_kollektiv_versionskontrollerad_mjukvaru_utvecking_med_git_och_Github_B.qmd
    - chapters/arbetsflödes_hanterings_program_Nextflow_del_3.qmd
    - chapters/1_program_utvecklade_i_en_specifik_hårdvarukonfiguration_skall_kunna_köras_i_vilken_som_helst_annan.qmd
    - chapters/container_hanteringsprogram_och_container_register.qmd

    - chapters/arbetsflödes_hanterings_program_Nextflow_del_4.qmd
    - chapters/nextflow_är_ett_programmeringsspråk.qmd
    - chapters/nextflow_är_ett_verktyg.qmd
    - chapters/nf_core_modules.qmd
    - chapters/nf_core_arbetsflöden_finns_på_github.qmd
    - chapters/arbetsflödes_hanterings_program_Nextflow_del_5.qmd
    - chapters/arbetsflödes_hanterings_program_Nextflow_sista.qmd
    - chapters/konfigurera_köra_och_debugga_nf_core_raredisease_arbetsfödet_från_kommando_linjen_på_en_HPC.qmd
    - chapters/vad_är_Seqera.qmd
    - chapters/hur_kan_ett_sådant_arbetsflöde_köras.qmd
    - chapters/arbetsflödet_och_programmen_som_det_omfattar_är_versionskontrollerade.qmd
    - chapters/skalbarhet.qmd
    - chapters/nextflow_arbetsflöden_som_följer_och_inte_följer_nf-core.qmd
    - chapters/3_Behov_av_kontinuerlig_utveckling_av_algoritmer_och_mjukvara.qmd
    - chapters/om_Seqera_igen.qmd
    - chapters/konfigurera_köra_och debugga nf_core_raredisease_arbetsfödet_på_Seqera.qmd
    - chapters/vill_du_veta_mer.qmd
    - chapters/länkar_online_bilder.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

