# 

## Varifrån kommer ideen om programmatiska arbetsflöden/workflows/pipelines

För program för analys av sekvenseringsdata har det alltid funnits två huvudsakliga alternativ. Det ena har varit att kommersiella programvaror där utvecklingen sker inom ett företag, gärna det företag som står för sekvenserings utrustningen, där utvecklarna får betalt för sitt utvecklingsarbete. Det andra har varit att forskare har utvecklat program för egen räknings och sedan gjort dem tillgänglig för resten av världen under en licens som innebär att de kan användas gratis. Gratis programmet tenderar att vara små och utföra enskilda uppgifter och har genererats i stora mängder och ofta så väljs ett fåtal ut efter benchmarkingstudier. Man får då ett antal smaå progaram som utför varje enskild uppgift väldigt bra, men som måste sättas ihop i en kedja av program, ett bioinformatiskt arbetsföde, för att utföra hela analysuppgiften. Från sekvenserings-output till annoterade varianter som är klara för tolkning. De förstnämnda programmen tenderar att vara monolitiska peka och klick program utan någon större möjlighet för användarna nedströms att se vad som pågår under huven. Användaren får garantier av företaget att programmet gör det som efterfrågas, programmet ges input och genererar output.

Det att sätta ihop små program som utför enskilda uppgifter på ett bra eller tom ulitmat sätt har länga varit princip tillämpad i Unix/Linux miljön och visat sig vara ett framgångs recept av många olika anledningar. En av dem är att det lämpar sig för ostrukturerat samarbeta som det ofta är frågan om utanför en företags miljö. Det har med stor sannolikhet format iden om sättet som bioinformatiska gratis programvaror sammanfogas till större så kallade arbetsflöden eller pipelines.

Sekvensdata för ett humant genome tar stor plats på en hårddisk. För att aligna shortread sekvenser från ett helt mänskligt DNA så krävas mycket RAM minne och stor processor kraft och parallell processering är nödvändig. Hårdvaran som lämpar sig för analys av mänskliga helgenom sekvenser framför allt om man förväntar sig analys av många personers DNA per tidsenhet är vad som kallas HPC eller moln.

Nog för att pipelines har fördelar men de kommer också med utmaningar.

Programmerings arbetsflöden spelar en stor roll för forskings generellt för LifeScience specifikt och ser ut att komma att spela en central roll för Precisions Diagnostik, lokalt, nationellt och internationellt

## 

## Exempel från Sällsynta diagnoser - Del i ett större arbetsflöde

Här visas en schematisering av ett arbetsflöde på PL-rd. Schematiskeringen är förenklad och framför allt i det bioinformatiska flöden så har saker som tex identifiering av kopietalsförändringar utelämnats.

### Manuell/fysisk del

1.  Det startar med att prov kommer in

2.  DNA extraheras och bibliotek prepareras och lastas på en sekvenseringsmaskin

### Bioinformatisk del

1.  Sekvenseringsmaskinen skriver sekvens och kvalitetsdata data, ursprungligen ofta i nått företagsspecifikt format.

2.  Text filer, sk fastq-filer, en för varje sekvenserad fragment, med sekvens och kvalitetsdata tillverkas.

3.  Fragment-sekvens-datan filtreras och och alignas (radas upp) mot ett referensgenome

4.  Varianter i förhållande till referens genomet identifieras och sparas i en Variant Call File VCF.

5.  Varianterna annoteras med information som möjliggör efterkommande tolkning

### Samarbete människa maskin

1.  Tolkning

## Liknande arbetsflöden finns ju också för Patologi och Mikrogrupperna

Det visade arbetsflödet skall klara helgenoms analyser vilket gör bioinformatik delen mer resurskrävande än de övriga flödena.

## Arbetsflödeshantering

Växte först fram ur ett behov av att tillskriva roller till olika delar av arbetsflödet

## Arbetsflödeshateringssystem (översättnging wikipedia eng)

Ett [arbetsflödeshanteringssystem](https://en-m-wikipedia-org.translate.goog/wiki/Workflow_management_system?_x_tr_sl=en&_x_tr_tl=sv&_x_tr_hl=en&_x_tr_pto=wapp "Arbetsflödeshanteringssystem") (WfMS) är ett mjukvarusystem för att sätta upp, utföra och övervaka en definierad sekvens av processer och uppgifter, med de breda målen att öka produktiviteten, minska kostnaderna, bli mer agil och förbättra informationsutbytet inom en organisation. ^[\[ 19 \]](https://en-m-wikipedia-org.translate.goog/wiki/Workflow?_x_tr_sl=en&_x_tr_tl=sv&_x_tr_hl=en&_x_tr_pto=wapp#cite_note-ElmagarmidWorkflow12-19)^ Dessa system kan vara processcentrerade eller datacentrerade, och de kan representera arbetsflödet som grafiska kartor. Ett arbetsflödeshanteringssystem kan också inkludera ett utbyggbart gränssnitt så att externa mjukvaruapplikationer kan integreras och ge stöd för bredare arbetsflöden som ger snabbare svarstider och förbättrad produktivitet

## Nf-core raredisease arbetsflödet

Detta är det arbetsflödet som jag har försökt få att fungera sen jag började jobba här. Det anses vara det mest komplicerade av alla de 121 (as of 2024-01-08) arbetslföden som nf-core konsortet har utvecklat. Det finns ett stort itressea av at få det att fungera inte bara i Sverige men globalt och inom företeg Seqera som växt fram från skaparna av Nextflow.

pipelinen är byggt med arbetsflödes hanterings programmet Nextflow.

Eftersom pipelinen är svår att köra med helgenomdata så är det svårt att uppskatta vilka resurser som kräs för att köra det.

nf-core/raredisease consists of several tools used for various purposes. For convenience, we have grouped those tools under the following categories:

1.  Alignment (bwamem2/bwa/bwameme/Sentieon BWA mem)

2.  QC stats from the alignment files

3.  Repeat expansions (ExpansionsHunter & Stranger)

4.  Variant calling - SNV (DeepVariant/Sentieon DNAscope)

5.  Variant calling - Structural variants (SV) (Tiddit & Manta)

6.  Copy number variant calling (GATK’s GermlineCNVCaller)

7.  SNV annotation & ranking (rohcall, vcfanno, ensembl VEP, GENMOD)

8.  SV annotation & ranking (SVDB query, ensembl VEP, GENMOD)

9.  Mitochondrial annotation

Detta är alltså bara en kategori indelning av de program som görs. Det flesta av programmen som körs behöver specifik input data vilket i nuläget gör det väldigt komplicerat att färdigställ input för en körning.
