# Sällsynta diagnoser - arbetsflöde - utvecklat av nf-core

Detta är det arbetsflödet som jag har försökt få att fungera sen jag började jobba här. Det anses vara det mest komplicerade av alla de 121 (as of 2024-01-08) arbetslföden som nf-core konsortet har utvecklat. Det finns ett stort itressea av at få det att fungera inte bara i Sverige men globalt och inom företeg Seqera som växt fram från skaparna av Nextflow.

pipelinen är byggt med arbetsflödes hanterings programmet Nextflow.

Eftersom pipelinen är svår att köra med helgenomdata så är det svårt att uppskatta vilka resurser som kräs för att köra det.

nf-core/raredisease consists of several tools used for various purposes. For convenience, we have grouped those tools under the following categories:

1.  Alignment (bwamem2/bwa/bwameme/Sentieon BWA mem)

2.  QC stats from the alignment files

3.  Repeat expansions (ExpansionsHunter & Stranger)

4.  Variant calling - SNV (DeepVariant/Sentieon DNAscope)

5.  Variant calling - Structural variants (SV) (Tiddit & Manta)

6.  Copy number variant calling (GATK’s GermlineCNVCaller)

7.  SNV annotation & ranking (rohcall, vcfanno, ensembl VEP, GENMOD)

8.  SV annotation & ranking (SVDB query, ensembl VEP, GENMOD)

9.  Mitochondrial annotation

Detta är alltså bara en kategori indelning av de program som görs. Det flesta av programmen som körs behöver specifik input data vilket i nuläget gör det väldigt komplicerat att färdigställ input för en körning.
